#!/bin/bash

# This script is used to build the "ebs-demo" container image into a tarball.

set -eux

CUR_DIR=$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)

IMAGE_REF=amazon/ebs-demo:latest
mkdir -p tar-files
IMAGE_TAR=tar-files/ebs-demo.tar

cp "bin/ebs-demo-binary" ./ebs-demo-binary
docker build -t "${IMAGE_REF}" -f Dockerfile .
docker save "${IMAGE_REF}" -o "${IMAGE_TAR}"
rm ./ebs-demo-binary
rm -rf bin/
